name: qr_users
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  lottie: ^0.7.0+1
  flutter_custom_clippers: ^1.1.2
  path_provider: ^1.1.0
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.1.0
  provider: ^4.3.2+2
  cached_network_image: ^2.4.1
  http: ^0.12.2
  intl: ^0.16.1
  flutter_launcher_icons: ^0.8.1
  geolocator: ^6.2.1
  fluttertoast: ^7.1.6
  camera: ^0.5.8+11
  cron: ^0.2.4
  audioplayers: ^0.13.0
  permission_handler: ^5.0.1+1
  trust_location: ^2.0.11
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.9
  flutter_image_compress: ^0.7.0
  curved_navigation_bar: ^0.3.4
  image_pickers: ^1.0.8+7
  image_picker: 0.6.2+3
  date_time_picker: ^1.1.1
  google_maps_flutter: ^0.5.33
  date_range_picker: ^1.0.7
  autocomplete_textfield: ^1.7.3
  typicons_flutter: ^0.3.1
  font_awesome_flutter: ^8.10.0
  syncfusion_flutter_xlsio: ^18.4.41
  ext_storage: ^1.0.3
  open_file: ^3.0.3
  pull_to_refresh: 1.6.5
  geocoding: ^1.0.5
  share: ^0.6.5+4
  intl_phone_number_input: ^0.6.0
  flutter_screenutil: ^4.0.3+3  
  fluttercontactpicker: ^4.2.1
  device_info: ^0.4.0+4
  get_mac: ^0.0.1
  flutter_secure_storage:
  auto_size_text: ^2.1.0
  flutter_jailbreak_detection: ^1.4.0
  connectivity: ^3.0.6
  shimmer: ^2.0.0
  animate_do: ^2.0.0
  searchable_dropdown: ^1.1.3
  image_face: ^1.1.0
  firebase_ml_vision: ^0.9.2+1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  meta: ^1.1.8
  expandable: ^5.0.1
  # google_ml_kit: ^0.5.0
  tflite_flutter:
  tflite_flutter_helper:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/image.png"
  image_path_ios: "resources/imgIos.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/
    - assets/
    - resources/fonts/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Almarai-Regular
      fonts:
        - asset: resources/fonts/Almarai-Regular.ttf
      
   
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
